/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_biocis_utils_SuperEnhancerCheck */

#ifndef _Included_com_biocis_utils_SuperEnhancerCheck
#define _Included_com_biocis_utils_SuperEnhancerCheck
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_biocis_utils_SuperEnhancerCheck
 * Method:    PerformCheck
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_biocis_utils_SuperEnhancerCheck_PerformCheck
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
