/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_biocis_utils_SuperEnhancer */

#ifndef _Included_com_biocis_utils_SuperEnhancer
#define _Included_com_biocis_utils_SuperEnhancer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_biocis_utils_SuperEnhancer
 * Method:    PerformSearch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_biocis_utils_SuperEnhancer_PerformSearch
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
