/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EnhancerCheck */

#ifndef _Included_EnhancerCheck
#define _Included_EnhancerCheck
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     EnhancerCheck
 * Method:    PerformCheck
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SuperEnhancerCheck_PerformCheck
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
