/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Enhancer */

#ifndef _Included_Enhancer
#define _Included_Enhancer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Enhancer
 * Method:    PerformSearch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SuperEnhancer_PerformSearch
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
