/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Stemming */

#ifndef _Included_Stemming
#define _Included_Stemming
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Stemming
 * Method:    stemming
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Stemming_stemming
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
